# Node Permissioning
nodes-allowlist=[]

# Account Permissioning
accounts-allowlist=[]

# Admin Account for managing permissions
accounts-permissioning-contract-address=""
nodes-permissioning-contract-address=""

# Contract-based permissioning enabled
contract-based-permissioning=true

# Smart contract version
smart-contract-version="2"

# Permissioning configuration
permissioning-config-file-enabled=true

# Onchain permissioning enabled
onchain-permissioning-enabled=true

# Metrics for permissioning
metrics-enabled=true

# Permissioning service port
permissioning-service-port=8888

# Permissioning service host
permissioning-service-host="0.0.0.0"

# Local permissioning enabled
local-permissioning-enabled=true

# Permissioning accept/deny all by default
permissioning-accept-all=false 