global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'besu'
    static_configs:
      - targets: ['localhost:9545']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'privacy'
    static_configs:
      - targets: ['localhost:9546']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'validators'
    static_configs:
      - targets:
        - 'validator1:9545'
        - 'validator2:9545'
        - 'validator3:9545'
        - 'validator4:9545'

  - job_name: 'bridges'
    static_configs:
      - targets: ['localhost:9547']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'defi-protocols'
    static_configs:
      - targets: ['localhost:9548']
    metrics_path: '/metrics'
    scheme: 'http' 