name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.15.4
      
      - name: Check for updates
        id: ncu
        run: |
          pnpm add -g npm-check-updates
          ncu --packageFile package.json --format json > updates.json
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            Automated dependency updates.
            
            Updates found:
            ```json
            $(cat updates.json)
            ```
            
            Please review the changes and merge if tests pass.
          branch: "deps/weekly-update"
          base: "main"
          labels: "dependencies"
          
      - name: Run security audit
        run: pnpm audit
        
      - name: Run Snyk scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
