name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest
    environment: testnet
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8.15.4
        run_install: false
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Deploy to testnet
      run: pnpm run deploy:testnet
      env:
        PRIVATE_KEY: ${{ secrets.TESTNET_PRIVATE_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

  deploy-mainnet:
    needs: deploy-testnet
    runs-on: ubuntu-latest
    environment: mainnet
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8.15.4
        run_install: false
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Deploy to mainnet
      run: |
        echo "Deploying version ${GITHUB_REF#refs/tags/} to mainnet"
        pnpm run deploy:mainnet
      env:
        PRIVATE_KEY: ${{ secrets.MAINNET_PRIVATE_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          deployments/mainnet.json
          artifacts/*.json
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              